name: Pull Request Demo

run-name: ${{ github.actor }} is learning GitHub Auto PR Action 
on:
  pull_request_review:
    types:
      - submitted

jobs:
  on-approval:
    if: github.event.review.state == 'approved'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4

      - name: Output for Job 1
        run: echo "Hello from Job 1"


