#name of YAML files
name: pull request demo

on:
  workflow_dispatch:
    inputs:
      name:
        # Friendly description to be shown in the UI instead of 'name'
        description: 'Your Name'
        # Default value if no value is explicitly provided
        default: 'Joe Bloggs'
        # Input has to be provided for the workflow to run
        required: true
        type: string

jobs:
  pull-request:
    runs-on: ubuntu-lastest
   
    # defaults:
    #   run:
    #     working-directory: my-project

    steps:
      # - name: Checkout code
      #   uses: actions/checkout@v2

      # - name: Set up Python
      #   uses: actions/setup-python@v5 
      #   with:
      #     python-version: '3.12.8'

      - name: Print Hello World
        run: echo "Hello, world!"
 